controller_list:
  - name: manipulator
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  - name: hand
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [finger_joint1]
