controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_hand_controller
    joints:
      - finger_joint1
      - finger_joint2
