# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 8.03
    has_acceleration_limits: true
    max_acceleration: 12.03
    min_position: -0.8
    max_position: 0.8
  joint_2:
    has_velocity_limits: true
    max_velocity: 8.03
    has_acceleration_limits: true
    max_acceleration: 12.03
    min_position: -1.9
    max_position: 2
  joint_3:
    has_velocity_limits: true
    max_velocity: 9.08
    has_acceleration_limits: true
    max_acceleration: 12.08
  joint_4:
    has_velocity_limits: true
    max_velocity: 9.77
    has_acceleration_limits: true
    max_acceleration: 12.77
    min_position: -1
    max_position: 1
  joint_5:
    has_velocity_limits: true
    max_velocity: 9.77
    has_acceleration_limits: true
    max_acceleration: 12.77
    min_position: -2
    max_position: 2
  joint_6:
    has_velocity_limits: true
    max_velocity: 15.71
    has_acceleration_limits: true
    max_acceleration: 9.35
    min_position: -2
    max_position: 2
